# Configuration of Academic
# Documentation: https://sourcethemes.com/academic/
languageCode = "en-gb"

# The URL of your website.
# End your URL with a `/` trailing slash, e.g. `https://example.com/`.
baseurl = "https://laurajanegraham.github.io/"

# Title of your site
title = "Laura Jane Graham"

# Your copyright notice - appears in site footer.
# To display a copyright symbol, type `&copy;`.
copyright = "&copy; 2018"
theme = "hugo-academic"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
